name: dart_big5
description: >-
  This package provides encode, decode method for big5.
version: 0.0.5+1
repository: https://github.com/KNightING/dart-big5

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.18.2
